//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PckStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PckStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _1_91_colours {
            get {
                object obj = ResourceManager.GetObject("_1_91_colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddTexture {
            get {
                object obj = ResourceManager.GetObject("AddTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap armor {
            get {
                object obj = ResourceManager.GetObject("armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ARROW {
            get {
                object obj = ResourceManager.GetObject("ARROW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BEHAVIOURS_ICON {
            get {
                object obj = ResourceManager.GetObject("BEHAVIOURS_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] binka_encode {
            get {
                object obj = ResourceManager.GetObject("binka_encode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BINKA_ICON {
            get {
                object obj = ResourceManager.GetObject("BINKA_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] binkawin {
            get {
                object obj = ResourceManager.GetObject("binkawin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CAPE_ICON {
            get {
                object obj = ResourceManager.GetObject("CAPE_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.0.0.0
        ///====================  
        ///
        ///-Added .3dst (3DS Texture) support  
        ///-Semi-added Sub-Pck editing  
        ///-Add an edit all properties tool item  
        ///-Skin Preview has been improved  
        ///-Added Pack Icon Injection into .arc file  
        ///-Improved COL Editor  
        ///-Massive codebase overhaul and optimization lead by miku-666 (aka NessieHax)!!!  
        ///-Some UI redesigned by yaboiFoxx  
        ///-Improved the changelog!  
        ///-New icons for each of the file types, with unique image icons for skin, texture, and cape files  
        ///-Added the abili [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CHANGELOG {
            get {
                return ResourceManager.GetString("CHANGELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap changeTile {
            get {
                object obj = ResourceManager.GetObject("changeTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap classic_template {
            get {
                object obj = ResourceManager.GetObject("classic_template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap COL_ICON {
            get {
                object obj = ResourceManager.GetObject("COL_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DefaultSkyTexture {
            get {
                object obj = ResourceManager.GetObject("DefaultSkyTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Discord {
            get {
                object obj = ResourceManager.GetObject("Discord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap entities_atlas {
            get {
                object obj = ResourceManager.GetObject("entities_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ENTITY_MATERIALS_ICON {
            get {
                object obj = ResourceManager.GetObject("ENTITY_MATERIALS_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT&quot;: &quot;Entity data research by NessieHax (Miku-666) and MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;area_effect_cloud&quot;,
        ///			&quot;displayName&quot;: &quot;Area Effect Cloud / Particle&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;armor_stand&quot;,
        ///			&quot;displayName&quot;: &quot;Armor Stand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;arrow&quot;,
        ///			&quot;displayName&quot;: &quot;Arrow&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;bat&quot;,
        ///			&quot;displayName&quot;: &quot;Bat&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;blaze&quot;,
        ///			&quot;displayName&quot;: &quot;Blaze&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;boat&quot;,
        ///			&quot;display [rest of string was truncated]&quot;;.
        /// </summary>
        public static string entityBehavioursData {
            get {
                return ResourceManager.GetString("entityBehavioursData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT&quot;: &quot;Entity data research by NessieHax (Miku-666) and MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;&quot;,
        ///			&quot;displayName&quot;: &quot;&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;&quot;,
        ///			&quot;displayName&quot;: &quot;&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;&quot;,
        ///			&quot;displayName&quot;: &quot;&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;bat&quot;,
        ///			&quot;displayName&quot;: &quot;Bat&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;blaze_head&quot;,
        ///			&quot;displayName&quot;: &quot;Blaze&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;&quot;,
        ///			&quot;displayName&quot;: &quot;&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;cat&quot;,
        ///			&quot;displayName&quot;: &quot;Cat [PS4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string entityMaterialsData {
            get {
                return ResourceManager.GetString("entityMaterialsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT&quot;: &quot;Entity data research by NessieHax (Miku-666) and MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;&quot;,
        ///			&quot;displayName&quot;: &quot;&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;&quot;,
        ///			&quot;displayName&quot;: &quot;&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;&quot;,
        ///			&quot;displayName&quot;: &quot;&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;bat&quot;,
        ///			&quot;displayName&quot;: &quot;Bat&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;blaze&quot;,
        ///			&quot;displayName&quot;: &quot;Blaze&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;boat&quot;,
        ///			&quot;displayName&quot;: &quot;Boat&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;cat&quot;,
        ///			&quot;displayName&quot;: &quot;Cat [ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string entityModelsData {
            get {
                return ResourceManager.GetString("entityModelsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_copy {
            get {
                object obj = ResourceManager.GetObject("file_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_delete {
            get {
                object obj = ResourceManager.GetObject("file_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_empty {
            get {
                object obj = ResourceManager.GetObject("file_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_export {
            get {
                object obj = ResourceManager.GetObject("file_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_import {
            get {
                object obj = ResourceManager.GetObject("file_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_new {
            get {
                object obj = ResourceManager.GetObject("file_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_paste {
            get {
                object obj = ResourceManager.GetObject("file_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_restore {
            get {
                object obj = ResourceManager.GetObject("file_restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) out vec4 color;
        ///
        ///uniform sampler2D screenTexture;
        ///
        ///in vec2 texCoords;
        ///
        ///void main()
        ///{
        ///	vec3 texColor = texture(screenTexture, texCoords).rgb;
        ///	color = vec4(texColor, 1.0);
        ///}.
        /// </summary>
        public static string framebufferFragmentShader {
            get {
                return ResourceManager.GetString("framebufferFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) in vec4 a_PosAndTexCoord;
        ///
        ///out vec2 texCoords;
        ///
        ///void main()
        ///{
        ///	vec2 pos = a_PosAndTexCoord.xy;
        ///	texCoords = a_PosAndTexCoord.zw;
        ///	gl_Position = vec4(pos, 0.0, 1.0);
        ///};.
        /// </summary>
        public static string framebufferVertexShader {
            get {
                return ResourceManager.GetString("framebufferVertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GRF_ICON {
            get {
                object obj = ResourceManager.GetObject("GRF_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GRH_ICON {
            get {
                object obj = ResourceManager.GetObject("GRH_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HamburgerMenuIcon {
            get {
                object obj = ResourceManager.GetObject("HamburgerMenuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMAGE_ICON {
            get {
                object obj = ResourceManager.GetObject("IMAGE_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap INFO_ICON {
            get {
                object obj = ResourceManager.GetObject("INFO_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOC_ICON {
            get {
                object obj = ResourceManager.GetObject("LOC_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MODELS_ICON {
            get {
                object obj = ResourceManager.GetObject("MODELS_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mss32 {
            get {
                object obj = ResourceManager.GetObject("mss32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap music {
            get {
                object obj = ResourceManager.GetObject("music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NoImageFound {
            get {
                object obj = ResourceManager.GetObject("NoImageFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pack {
            get {
                object obj = ResourceManager.GetObject("pack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PCK_ICON {
            get {
                object obj = ResourceManager.GetObject("PCK_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pckClosed {
            get {
                object obj = ResourceManager.GetObject("pckClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pckDrop {
            get {
                object obj = ResourceManager.GetObject("pckDrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pckOpen {
            get {
                object obj = ResourceManager.GetObject("pckOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) out vec4 FragColor;
        ///
        ///uniform vec4 BlendColor;
        ///uniform float Intensity;
        ///
        ///in vec4 color;
        ///
        ///void main()
        ///{
        ///	FragColor = vec4((color * BlendColor).rgb, Intensity);
        ///}.
        /// </summary>
        public static string plainColorFragmentShader {
            get {
                return ResourceManager.GetString("plainColorFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) in vec4 a_Pos;
        ///layout(location = 1) in vec4 a_Color;
        ///
        ///uniform mat4 ViewProjection;
        ///uniform mat4 Transform;
        ///
        ///out vec4 color;
        ///
        ///void main()
        ///{
        ///	color = a_Color;
        ///	gl_Position = ViewProjection * Transform * vec4(a_Pos.xyz, 1.0);
        ///};.
        /// </summary>
        public static string plainColorVertexShader {
            get {
                return ResourceManager.GetString("plainColorVertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ProjectLogo {
            get {
                object obj = ResourceManager.GetObject("ProjectLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PS3 {
            get {
                object obj = ResourceManager.GetObject("PS3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ranch {
            get {
                object obj = ResourceManager.GetObject("ranch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Replace {
            get {
                object obj = ResourceManager.GetObject("Replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SKIN_ICON {
            get {
                object obj = ResourceManager.GetObject("SKIN_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SKINS_ICON {
            get {
                object obj = ResourceManager.GetObject("SKINS_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) out vec4 color;
        ///
        ///uniform samplerCube skybox;
        ///uniform float brightness;
        ///
        ///in vec3 texCoords;
        ///
        ///void main()
        ///{
        ///	color = vec4(texture(skybox, texCoords).rgb * clamp(brightness, 0.0, 1.0), 1.0);
        ///}.
        /// </summary>
        public static string skyboxFragmentShader {
            get {
                return ResourceManager.GetString("skyboxFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) in vec4 a_Pos;
        ///
        ///uniform mat4 ViewProjection;
        ///
        ///out vec3 texCoords;
        ///
        ///void main()
        ///{
        ///	vec4 pos = ViewProjection * a_Pos;
        ///	gl_Position = vec4(pos.x, pos.y, pos.ww);
        ///	texCoords = vec3(a_Pos.xy, -a_Pos.z);
        ///};.
        /// </summary>
        public static string skyboxVertexShader {
            get {
                return ResourceManager.GetString("skyboxVertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slim_template {
            get {
                object obj = ResourceManager.GetObject("slim_template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TEXTURE_ICON {
            get {
                object obj = ResourceManager.GetObject("TEXTURE_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) out vec4 color;
        ///
        ///uniform sampler2D Texture;
        ///
        ///in vec2 o_TillingFactor;
        ///in vec2 o_TexCoord;
        ///
        ///void main()
        ///{
        ///	vec4 result = texture(Texture, o_TexCoord * o_TillingFactor);
        ///	if (result.a &lt;= 0.0)
        ///		discard;
        ///	color = result;
        ///};.
        /// </summary>
        public static string texturedCubeFragmentShader {
            get {
                return ResourceManager.GetString("texturedCubeFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout (triangles) in;
        ///layout (triangle_strip, max_vertices=3) out;
        ///
        ///uniform vec2 TexSize;
        ///
        ///out vec2 o_TexCoord;
        ///out vec2 o_TillingFactor;
        ///
        ///in geometryData
        ///{
        ///	vec2 TexCoord;
        ///} dataIn[];
        ///
        ///void FixUV()
        ///{
        ///	bool isXBad =
        ///		dataIn[0].TexCoord.x &gt;= TexSize.x &amp;&amp;
        ///		dataIn[1].TexCoord.x &gt;= TexSize.x &amp;&amp;
        ///		dataIn[2].TexCoord.x &gt;= TexSize.x;
        ///
        ///	gl_Position = gl_in[0].gl_Position;
        ///	o_TexCoord = dataIn[0].TexCoord;
        ///	if (isXBad)
        ///		o_TexCoord.x = mod(o_TexCoord.x, TexSize.x);
        ///	Em [rest of string was truncated]&quot;;.
        /// </summary>
        public static string texturedCubeGeometryShader {
            get {
                return ResourceManager.GetString("texturedCubeGeometryShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) in vec3 vertexPosition;
        ///layout(location = 1) in vec2 texCoord;
        ///
        ///uniform mat4 ViewProjection;
        ///uniform mat4 Transform;
        ///
        ///out geometryData
        ///{
        ///	vec2 TexCoord;
        ///} dataOut;
        ///
        ///void main()
        ///{
        ///	dataOut.TexCoord = texCoord;
        ///	gl_Position = ViewProjection * Transform * vec4(vertexPosition, 1.0);
        ///};.
        /// </summary>
        public static string texturedCubeVertexShader {
            get {
                return ResourceManager.GetString("texturedCubeVertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trello {
            get {
                object obj = ResourceManager.GetObject("trello", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu12colours {
            get {
                object obj = ResourceManager.GetObject("tu12colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu13colours {
            get {
                object obj = ResourceManager.GetObject("tu13colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu14colours {
            get {
                object obj = ResourceManager.GetObject("tu14colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu19colours {
            get {
                object obj = ResourceManager.GetObject("tu19colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu31colours {
            get {
                object obj = ResourceManager.GetObject("tu31colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu32colours {
            get {
                object obj = ResourceManager.GetObject("tu32colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu43colours {
            get {
                object obj = ResourceManager.GetObject("tu43colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu46colours {
            get {
                object obj = ResourceManager.GetObject("tu46colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu51colours {
            get {
                object obj = ResourceManager.GetObject("tu51colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu53colours {
            get {
                object obj = ResourceManager.GetObject("tu53colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu54colours {
            get {
                object obj = ResourceManager.GetObject("tu54colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tu69colours {
            get {
                object obj = ResourceManager.GetObject("tu69colours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WiiU {
            get {
                object obj = ResourceManager.GetObject("WiiU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Xbox {
            get {
                object obj = ResourceManager.GetObject("Xbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Youtube {
            get {
                object obj = ResourceManager.GetObject("Youtube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZUnknown {
            get {
                object obj = ResourceManager.GetObject("ZUnknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZZFolder {
            get {
                object obj = ResourceManager.GetObject("ZZFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
