//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PckStudio.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PckStudio.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap additional_map_icons_atlas {
            get {
                object obj = ResourceManager.GetObject("additional_map_icons_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;base&quot;,
        ///			&quot;displayName&quot;: &quot;Base&quot;,
        ///			&quot;hasColourEntry&quot;: true,
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;Banner_White&quot;,
        ///				&quot;variants&quot;: [
        ///					&quot;Banner_Black&quot;,
        ///					&quot;Banner_Blue&quot;,
        ///					&quot;Banner_Brown&quot;,
        ///					&quot;Banner_Cyan&quot;,
        ///					&quot;Banner_Gray&quot;,
        ///					&quot;Banner_Green&quot;,
        ///					&quot;Banner_Light_Blue&quot;,
        ///					&quot;Banner_Lime&quot;,
        ///					&quot;Banner_Magenta&quot;,
        ///					&quot;Banner_Orange&quot;,
        ///					&quot;Banner_Pink&quot;,
        ///					&quot;Banner_Purple&quot;,
        ///					&quot;Banner_Red&quot;,
        ///					&quot;Ban [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bannerData {
            get {
                return ResourceManager.GetString("bannerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap banners_atlas {
            get {
                object obj = ResourceManager.GetObject("banners_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;Tile data research by MattNL&quot;,
        ///	&quot;COMMENT_2&quot;: &quot;JSON by PhoenixARC, MattNL, and NessieHax (Miku-666)&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;grass_top&quot;,
        ///			&quot;displayName&quot;: &quot;Grass Block (Top)&quot;,
        ///			&quot;hasColourEntry&quot;: true,
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;Grass_Common&quot;,
        ///				&quot;variants&quot;: [
        ///					&quot;Grass_Common&quot;,
        ///					&quot;Grass_Mesa&quot;,
        ///					&quot;Grass_Swamp1&quot;,
        ///					&quot;Grass_Swamp2&quot;
        ///				]
        ///			}
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;stone&quot;,
        ///			&quot;displayName&quot;: &quot;Stone&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string blockData {
            get {
                return ResourceManager.GetString("blockData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comparison {
            get {
                object obj = ResourceManager.GetObject("Comparison", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap experience_orbs_atlas {
            get {
                object obj = ResourceManager.GetObject("experience_orbs_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;experience_orb_0&quot;,
        ///			&quot;displayName&quot;: &quot;Experience Orb (Size 1)&quot;,
        ///			&quot;hasColourEntry&quot;: true,
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;experience_orb&quot;,
        ///				&quot;variants&quot;: [&quot;experience_orb&quot;]
        ///			}
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;experience_orb_1&quot;,
        ///			&quot;displayName&quot;: &quot;Experience Orb (Size 2)&quot;,
        ///			&quot;hasColourEntry&quot;: true,
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;experience_orb&quot;,
        ///				&quot;variants&quot;: [&quot;experience_orb&quot;]
        ///			}
        ///		},
        ///		{
        ///			&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string experienceOrbData {
            get {
                return ResourceManager.GetString("experienceOrbData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;explosion_0&quot;,
        ///			&quot;displayName&quot;: &quot;Explosion (Stage 1)&quot;,
        ///			&quot;hasColourEntry&quot;: true,
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;Particle_Explode&quot;,
        ///				&quot;variants&quot;: [
        ///					&quot;Particle_Explode&quot;,
        ///					&quot;Particle_HugeExplosion&quot;
        ///				]
        ///			}
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;explosion_1&quot;,
        ///			&quot;displayName&quot;: &quot;Explosion (Stage 2)&quot;,
        ///			&quot;hasColourEntry&quot;: true,
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;Particle_Explode&quot;,
        ///				&quot;variants&quot;: [
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string explosionData {
            get {
                return ResourceManager.GetString("explosionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap explosions_atlas {
            get {
                object obj = ResourceManager.GetObject("explosions_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;Tile data research by MattNL&quot;,
        ///	&quot;COMMENT_2&quot;: &quot;JSON by PhoenixARC, MattNL, and NessieHax (Miku-666)&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;helmetCloth&quot;,
        ///			&quot;displayName&quot;: &quot;Leather Cap&quot;,
        ///			&quot;allowCustomColour&quot;: true,
        ///			&quot;hasColourEntry&quot;: true,
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;Armour_Default_Leather_Colour&quot;,
        ///				&quot;variants&quot;: [ &quot;Armour_Default_Leather_Colour&quot; ]
        ///			}
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;helmetChain&quot;,
        ///			&quot;displayName&quot;: &quot;Chain Helmet&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string itemData {
            get {
                return ResourceManager.GetString("itemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap items_atlas {
            get {
                object obj = ResourceManager.GetObject("items_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap map_icons_atlas {
            get {
                object obj = ResourceManager.GetObject("map_icons_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;player_1&quot;,
        ///			&quot;displayName&quot;: &quot;Player 1&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_2&quot;,
        ///			&quot;displayName&quot;: &quot;Player 2&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_3&quot;,
        ///			&quot;displayName&quot;: &quot;Player 3&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_4&quot;,
        ///			&quot;displayName&quot;: &quot;Player 4&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;target_x&quot;,
        ///			&quot;displayName&quot;: &quot;Unused&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;target_point&quot;,
        ///			&quot;displayName&quot;: &quot;Target Point (Unused)&quot;
        ///		},
        ///		{
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mapIconData {
            get {
                return ResourceManager.GetString("mapIconData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap moon_phases_atlas {
            get {
                object obj = ResourceManager.GetObject("moon_phases_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_0&quot;,
        ///			&quot;displayName&quot;: &quot;Full Moon&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_1&quot;,
        ///			&quot;displayName&quot;: &quot;Waning Gibbous&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_2&quot;,
        ///			&quot;displayName&quot;: &quot;Last Quarter&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_3&quot;,
        ///			&quot;displayName&quot;: &quot;Waning Crescent&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_4&quot;,
        ///			&quot;displayName&quot;: &quot;New Moon&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_5&quot;,
        ///			&quot;displayName&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string moonPhaseData {
            get {
                return ResourceManager.GetString("moonPhaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;Kebab&quot;,
        ///			&quot;displayName&quot;: &quot;\&quot;Kebab med tre pepperoni\&quot; by Kristoffer Zetterstrand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;Aztec&quot;,
        ///			&quot;displayName&quot;: &quot;\&quot;de_aztec\&quot; by Kristoffer Zetterstrand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;Alban&quot;,
        ///			&quot;displayName&quot;: &quot;\&quot;Albanian\&quot; by Kristoffer Zetterstrand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;Aztec2&quot;,
        ///			&quot;displayName&quot;: &quot;\&quot;de_aztec\&quot; by Kristoffer Zetterstrand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;Bomb&quot;,
        ///			&quot;disp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string paintingData {
            get {
                return ResourceManager.GetString("paintingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paintings_atlas {
            get {
                object obj = ResourceManager.GetObject("paintings_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;generic_0&quot;,
        ///			&quot;displayName&quot;: &quot;Generic (Stage 1)&quot;,
        ///			&quot;hasColourEntry&quot;: true,
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;None&quot;,
        ///				&quot;variants&quot;: [
        ///					&quot;None&quot;,
        ///					&quot;Particle_Smoke&quot;,
        ///					&quot;Particle_NetherPortal&quot;,
        ///					&quot;Particle_EnderPortal&quot;,
        ///					&quot;Particle_Ender&quot;,
        ///					&quot;Particle_DragonBreathMin&quot;,
        ///					&quot;Particle_DragonBreathMax&quot;
        ///				]
        ///			}
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;generic_1&quot;,
        ///			&quot;displayName&quot;: &quot;Generic (Stage 2)&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string particleData {
            get {
                return ResourceManager.GetString("particleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap particles_atlas {
            get {
                object obj = ResourceManager.GetObject("particles_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap terrain_atlas {
            get {
                object obj = ResourceManager.GetObject("terrain_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TexturePackIcon {
            get {
                object obj = ResourceManager.GetObject("TexturePackIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
