//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PckStudio.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PckStudio.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap additional_map_icons_atlas {
            get {
                object obj = ResourceManager.GetObject("additional_map_icons_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///  &quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;player_1_off_map&quot;,
        ///			&quot;displayName&quot;: &quot;Player 1 (Off Map)&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_2_off_map&quot;,
        ///			&quot;displayName&quot;: &quot;Player 2 (Off Map)&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_3_off_map&quot;,
        ///			&quot;displayName&quot;: &quot;Player 3 (Off Map)&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_4_off_map&quot;,
        ///			&quot;displayName&quot;: &quot;Player 4 (Off Map)&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;treasure&quot;,
        ///			&quot;displayName&quot;: &quot;Buried Treasure&quot;
        ///		},
        ///		{
        ///			&quot;interna [rest of string was truncated]&quot;;.
        /// </summary>
        public static string additionalMapiconsData {
            get {
                return ResourceManager.GetString("additionalMapiconsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;internalName&quot;: &quot;base&quot;,
        ///      &quot;displayName&quot;: &quot;Base&quot;,
        ///      &quot;colorKey&quot;: &quot;Banner_Color&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;border&quot;,
        ///      &quot;displayName&quot;: &quot;Bordure&quot;,
        ///      &quot;colorKey&quot;: &quot;Banner_Color&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;bricks&quot;,
        ///      &quot;displayName&quot;: &quot;Field Masoned&quot;,
        ///      &quot;colorKey&quot;: &quot;Banner_Color&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;circle&quot;,
        ///      &quot;displayName&quot;: &quot;Roundel&quot;,
        ///      &quot;colorKey&quot;: &quot;Banner_Color&quot;
        ///    }, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bannerData {
            get {
                return ResourceManager.GetString("bannerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap banners_atlas {
            get {
                object obj = ResourceManager.GetObject("banners_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;Tile data research by MattNL&quot;,
        ///	&quot;COMMENT_2&quot;: &quot;JSON by PhoenixARC, MattNL, and NessieHax (Miku-666)&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;grass_top&quot;,
        ///			&quot;displayName&quot;: &quot;Grass Block (Top)&quot;,
        ///
        ///			&quot;colourEntry&quot;: {
        ///				&quot;defaultName&quot;: &quot;Grass_Common&quot;,
        ///				&quot;colorCategory&quot;: [&quot;Grass&quot;]
        ///			}
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;stone&quot;,
        ///			&quot;displayName&quot;: &quot;Stone&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;dirt&quot;,
        ///			&quot;displayName&quot;: &quot;Dirt&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;grass_side&quot;,
        ///			&quot;displayName&quot;: &quot;Grass [rest of string was truncated]&quot;;.
        /// </summary>
        public static string blockData {
            get {
                return ResourceManager.GetString("blockData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap chain {
            get {
                object obj = ResourceManager.GetObject("chain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cloth {
            get {
                object obj = ResourceManager.GetObject("cloth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cloth_b {
            get {
                object obj = ResourceManager.GetObject("cloth_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clouds {
            get {
                object obj = ResourceManager.GetObject("clouds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Particle&quot;: {
        ///    &quot;variants&quot;: [
        ///      &quot;Particle_Smoke&quot;,
        ///      &quot;Particle_NetherPortal&quot;,
        ///      &quot;Particle_EnderPortal&quot;,
        ///      &quot;Particle_Ender&quot;,
        ///      &quot;Particle_DragonBreathMin&quot;,
        ///      &quot;Particle_DragonBreathMax&quot;
        ///    ]
        ///  },
        ///  &quot;Particle_EnchantmentTable&quot;: {
        ///    &quot;defaultName&quot;: &quot;Particle_EnchantmentTable&quot;
        ///  },
        ///  &quot;Particle_ScoreRing&quot;: {
        ///    &quot;variants&quot;: [
        ///      &quot;Particle_ScoreRing_Small&quot;,
        ///      &quot;Particle_ScoreRing_Medium&quot;,
        ///      &quot;Particle_ScoreRing_Large&quot;
        ///    ]
        ///  },
        ///  &quot;Potion_Effect&quot;: {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string colorEntries {
            get {
                return ResourceManager.GetString("colorEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comparison {
            get {
                object obj = ResourceManager.GetObject("Comparison", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap compass {
            get {
                object obj = ResourceManager.GetObject("compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;bat&quot;: {
        ///    &quot;textureSize&quot;: { &quot;X&quot;: 64, &quot;Y&quot;: 64 },
        ///    &quot;parts&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;head&quot;,
        ///        &quot;boxes&quot;: [
        ///          { &quot;pos&quot;: { &quot;X&quot;: -3, &quot;Y&quot;: -3, &quot;Z&quot;: -3 }, &quot;size&quot;: { &quot;X&quot;: 6, &quot;Y&quot;: 6, &quot;Z&quot;: 6 }, &quot;uv&quot;: { &quot;X&quot;: 0, &quot;Y&quot;: 0 } }
        ///        ]
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;body&quot;,
        ///        &quot;boxes&quot;: [
        ///          { &quot;pos&quot;: { &quot;X&quot;: -3, &quot;Y&quot;: 4, &quot;Z&quot;: -3 }, &quot;size&quot;: { &quot;X&quot;: 6, &quot;Y&quot;: 12, &quot;Z&quot;: 6 }, &quot;uv&quot;: { &quot;X&quot;: 0, &quot;Y&quot;: 16 } },
        ///          { &quot;pos&quot;: { &quot;X&quot;: -5, &quot;Y&quot;: 16, &quot;Z&quot;: 0 }, &quot;size&quot;: { &quot;X&quot;: 10, &quot;Y&quot;: 6, &quot;Z&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultModels {
            get {
                return ResourceManager.GetString("defaultModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap diamond {
            get {
                object obj = ResourceManager.GetObject("diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap experience_orbs_atlas {
            get {
                object obj = ResourceManager.GetObject("experience_orbs_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;experience_orb_0&quot;,
        ///			&quot;displayName&quot;: &quot;Experience Orb (Size 1)&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;experience_orb_1&quot;,
        ///			&quot;displayName&quot;: &quot;Experience Orb (Size 2)&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;experience_orb_2&quot;,
        ///			&quot;displayName&quot;: &quot;Experience Orb (Size 3)&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;experience_orb_3&quot;,
        ///			&quot;displayName&quot;: &quot;Experience Orb (Size 4)&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;experience_orb_4&quot;,
        ///			&quot;displayName&quot;: &quot;Experience Or [rest of string was truncated]&quot;;.
        /// </summary>
        public static string experienceOrbData {
            get {
                return ResourceManager.GetString("experienceOrbData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;internalName&quot;: &quot;explosion_0&quot;,
        ///      &quot;displayName&quot;: &quot;Explosion (Stage 1)&quot;,
        ///      &quot;colorKey&quot;: &quot;Particle_Explode&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;explosion_1&quot;,
        ///      &quot;displayName&quot;: &quot;Explosion (Stage 2)&quot;,
        ///      &quot;colorKey&quot;: &quot;Particle_Explode&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;explosion_2&quot;,
        ///      &quot;displayName&quot;: &quot;Explosion (Stage 3)&quot;,
        ///      &quot;colorKey&quot;: &quot;Particle_Explode&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;explosion_3&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string explosionData {
            get {
                return ResourceManager.GetString("explosionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap explosions_atlas {
            get {
                object obj = ResourceManager.GetObject("explosions_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fire_layer_0 {
            get {
                object obj = ResourceManager.GetObject("fire_layer_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fire_layer_1 {
            get {
                object obj = ResourceManager.GetObject("fire_layer_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gold {
            get {
                object obj = ResourceManager.GetObject("gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iron {
            get {
                object obj = ResourceManager.GetObject("iron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;Tile data research by MattNL&quot;,
        ///	&quot;COMMENT_2&quot;: &quot;JSON by PhoenixARC, MattNL, and NessieHax (Miku-666)&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;helmetCloth&quot;,
        ///			&quot;displayName&quot;: &quot;Leather Cap&quot;,
        ///			&quot;allowCustomColour&quot;: true,
        ///			&quot;colorKey&quot;: &quot;Armour_Default_Leather_Colour&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;helmetChain&quot;,
        ///			&quot;displayName&quot;: &quot;Chain Helmet&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;helmetIron&quot;,
        ///			&quot;displayName&quot;: &quot;Iron Helmet&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;helmetDiamond&quot;,
        ///			&quot;displayName&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string itemData {
            get {
                return ResourceManager.GetString("itemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap items_atlas {
            get {
                object obj = ResourceManager.GetObject("items_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Bow Pulling&quot;,
        ///    &quot;row&quot;: 5,
        ///    &quot;column&quot;: 6,
        ///    &quot;frameCount&quot;: 3,
        ///    &quot;frameTime&quot;: 6,
        ///    &quot;direction&quot;: 1
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Leather Cap&quot;,
        ///    &quot;row&quot;: 0,
        ///    &quot;column&quot;: 0,
        ///    &quot;overlay&quot;: { &quot;row&quot;: 0, &quot;column&quot;: 9 }
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Leather Tunic&quot;,
        ///    &quot;row&quot;: 0,
        ///    &quot;column&quot;: 1,
        ///    &quot;overlay&quot;: { &quot;row&quot;: 0, &quot;column&quot;: 10 }
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Leather Pants&quot;,
        ///    &quot;row&quot;: 0,
        ///    &quot;column&quot;: 2,
        ///    &quot;overlay&quot;: { &quot;row&quot;: 0, &quot;column&quot;: 11 }
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Leather  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string items_groups {
            get {
                return ResourceManager.GetString("items_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap map_icons_atlas {
            get {
                object obj = ResourceManager.GetObject("map_icons_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;player_1&quot;,
        ///			&quot;displayName&quot;: &quot;Player 1&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_2&quot;,
        ///			&quot;displayName&quot;: &quot;Player 2&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_3&quot;,
        ///			&quot;displayName&quot;: &quot;Player 3&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;player_4&quot;,
        ///			&quot;displayName&quot;: &quot;Player 4&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;target_x&quot;,
        ///			&quot;displayName&quot;: &quot;Unused&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;target_point&quot;,
        ///			&quot;displayName&quot;: &quot;Target Point (Unused)&quot;
        ///		},
        ///		{
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mapIconData {
            get {
                return ResourceManager.GetString("mapIconData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;bat&quot;: {
        ///    &quot;textureLocations&quot;: [
        ///      &quot;res/mob/bat&quot;
        ///    ],
        ///    &quot;materialName&quot;: &quot;bat&quot;,
        ///    &quot;parts&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;head&quot;,
        ///        &quot;children&quot;: [
        ///          { &quot;name&quot;: &quot;rightEar&quot; },
        ///          { &quot;name&quot;: &quot;leftEar&quot; }
        ///        ]
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;body&quot;,
        ///        &quot;children&quot;: [
        ///          {
        ///            &quot;name&quot;: &quot;rightWing&quot;,
        ///            &quot;children&quot;: [
        ///              { &quot;name&quot;: &quot;rightWingTip&quot; }
        ///            ]
        ///          },
        ///          {
        ///            &quot;name&quot;: &quot;leftWing&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string modelMetaData {
            get {
                return ResourceManager.GetString("modelMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap moon_phases_atlas {
            get {
                object obj = ResourceManager.GetObject("moon_phases_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_0&quot;,
        ///			&quot;displayName&quot;: &quot;Full Moon&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_1&quot;,
        ///			&quot;displayName&quot;: &quot;Waning Gibbous&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_2&quot;,
        ///			&quot;displayName&quot;: &quot;Last Quarter&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_3&quot;,
        ///			&quot;displayName&quot;: &quot;Waning Crescent&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_4&quot;,
        ///			&quot;displayName&quot;: &quot;New Moon&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;moon_phase_5&quot;,
        ///			&quot;displayName&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string moonPhaseData {
            get {
                return ResourceManager.GetString("moonPhaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;The Pool&quot;,
        ///    &quot;row&quot;: 0,
        ///    &quot;column&quot;: 2,
        ///    &quot;rowSpan&quot;: 2,
        ///    &quot;columnSpan&quot;: 1,
        ///    &quot;direction&quot;: 1
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Bonjour Monsiuer Courbet&quot;,
        ///    &quot;row&quot;: 2,
        ///    &quot;column&quot;: 2,
        ///    &quot;rowSpan&quot;: 2,
        ///    &quot;columnSpan&quot;: 1,
        ///    &quot;direction&quot;: 0
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Seaside&quot;,
        ///    &quot;row&quot;: 4,
        ///    &quot;column&quot;: 2,
        ///    &quot;rowSpan&quot;: 2,
        ///    &quot;columnSpan&quot;: 1,
        ///    &quot;direction&quot;: 0
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;sunset_dense&quot;,
        ///    &quot;row&quot;: 6,
        ///    &quot;column&quot;: 2,
        ///    &quot;rowSpan&quot;: 2,
        ///    &quot;columnSpan&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string painting_groups {
            get {
                return ResourceManager.GetString("painting_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///	&quot;entries&quot;: [
        ///		{
        ///			&quot;internalName&quot;: &quot;Kebab&quot;,
        ///			&quot;displayName&quot;: &quot;\&quot;Kebab med tre pepperoni\&quot; by Kristoffer Zetterstrand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;Aztec&quot;,
        ///			&quot;displayName&quot;: &quot;\&quot;de_aztec\&quot; by Kristoffer Zetterstrand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;Alban&quot;,
        ///			&quot;displayName&quot;: &quot;\&quot;Albanian\&quot; by Kristoffer Zetterstrand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;Aztec2&quot;,
        ///			&quot;displayName&quot;: &quot;\&quot;de_aztec\&quot; by Kristoffer Zetterstrand&quot;
        ///		},
        ///		{
        ///			&quot;internalName&quot;: &quot;Bomb&quot;,
        ///			&quot;disp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string paintingData {
            get {
                return ResourceManager.GetString("paintingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paintings_atlas {
            get {
                object obj = ResourceManager.GetObject("paintings_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;COMMENT_1&quot;: &quot;JSON by MattNL&quot;,
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;internalName&quot;: &quot;generic_0&quot;,
        ///      &quot;displayName&quot;: &quot;Generic (Stage 1)&quot;,
        ///      &quot;colorKey&quot;: &quot;Particle&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;generic_1&quot;,
        ///      &quot;displayName&quot;: &quot;Generic (Stage 2)&quot;,
        ///      &quot;colorKey&quot;: &quot;Particle&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;generic_2&quot;,
        ///      &quot;displayName&quot;: &quot;Generic (Stage 3)&quot;,
        ///      &quot;colorKey&quot;: &quot;Particle&quot;
        ///    },
        ///    {
        ///      &quot;internalName&quot;: &quot;generic_3&quot;,
        ///      &quot;displayName&quot;: &quot;Generic (Stage 4)&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string particleData {
            get {
                return ResourceManager.GetString("particleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap particles_atlas {
            get {
                object obj = ResourceManager.GetObject("particles_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Generic&quot;,
        ///    &quot;row&quot;: 0,
        ///    &quot;column&quot;: 0,
        ///    &quot;frameCount&quot;: 8,
        ///    &quot;frameTime&quot;: 2,
        ///    &quot;direction&quot;: 0
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Splash&quot;,
        ///    &quot;row&quot;: 3,
        ///    &quot;column&quot;: 1,
        ///    &quot;frameCount&quot;: 4,
        ///    &quot;frameTime&quot;: 2,
        ///    &quot;direction&quot;: 0
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Drip&quot;,
        ///    &quot;row&quot;: 0,
        ///    &quot;column&quot;: 7,
        ///    &quot;frameCount&quot;: 3,
        ///    &quot;frameTime&quot;: 4,
        ///    &quot;direction&quot;: 0
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Effect&quot;,
        ///    &quot;row&quot;: 0,
        ///    &quot;column&quot;: 8,
        ///    &quot;frameCount&quot;: 8,
        ///    &quot;frameTime&quot;: 2,
        ///    &quot;direction&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string particles_groups {
            get {
                return ResourceManager.GetString("particles_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rain {
            get {
                object obj = ResourceManager.GetObject("rain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap snow {
            get {
                object obj = ResourceManager.GetObject("snow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap terrain_atlas {
            get {
                object obj = ResourceManager.GetObject("terrain_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Oak Door&quot;,
        ///    &quot;row&quot;: 1,
        ///    &quot;column&quot;: 5,
        ///    &quot;rowSpan&quot;: 1,
        ///    &quot;columnSpan&quot;: 2,
        ///    &quot;direction&quot;: 1
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Iron Door&quot;,
        ///    &quot;row&quot;: 2,
        ///    &quot;column&quot;: 5,
        ///    &quot;rowSpan&quot;: 1,
        ///    &quot;columnSpan&quot;: 2,
        ///    &quot;direction&quot;: 1
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Acacia Door&quot;,
        ///    &quot;row&quot;: 0,
        ///    &quot;column&quot;: 23,
        ///    &quot;rowSpan&quot;: 1,
        ///    &quot;columnSpan&quot;: 2,
        ///    &quot;direction&quot;: 1
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Birch Door&quot;,
        ///    &quot;row&quot;: 1,
        ///    &quot;column&quot;: 23,
        ///    &quot;rowSpan&quot;: 1,
        ///    &quot;columnSpan&quot;: 2,
        ///    &quot;di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string terrain_groups {
            get {
                return ResourceManager.GetString("terrain_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TexturePackIcon {
            get {
                object obj = ResourceManager.GetObject("TexturePackIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap turtle {
            get {
                object obj = ResourceManager.GetObject("turtle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unknown_pack {
            get {
                object obj = ResourceManager.GetObject("unknown_pack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
