//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PckStuido.ModelSupport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PckStuido.ModelSupport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;bat&quot;: {
        ///    &quot;textureSize&quot;: { &quot;X&quot;: 64, &quot;Y&quot;: 64 },
        ///    &quot;parts&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;head&quot;,
        ///        &quot;boxes&quot;: [
        ///          { &quot;pos&quot;: { &quot;X&quot;: -3, &quot;Y&quot;: -3, &quot;Z&quot;: -3 }, &quot;size&quot;: { &quot;X&quot;: 6, &quot;Y&quot;: 6, &quot;Z&quot;: 6 }, &quot;uv&quot;: { &quot;X&quot;: 0, &quot;Y&quot;: 0 } }
        ///        ]
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;body&quot;,
        ///        &quot;boxes&quot;: [
        ///          { &quot;pos&quot;: { &quot;X&quot;: -3, &quot;Y&quot;: 4, &quot;Z&quot;: -3 }, &quot;size&quot;: { &quot;X&quot;: 6, &quot;Y&quot;: 12, &quot;Z&quot;: 6 }, &quot;uv&quot;: { &quot;X&quot;: 0, &quot;Y&quot;: 16 } },
        ///          { &quot;pos&quot;: { &quot;X&quot;: -5, &quot;Y&quot;: 16, &quot;Z&quot;: 0 }, &quot;size&quot;: { &quot;X&quot;: 10, &quot;Y&quot;: 6, &quot;Z&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultModels {
            get {
                return ResourceManager.GetString("defaultModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;bat&quot;: {
        ///    &quot;textureLocations&quot;: [
        ///      &quot;res/mob/bat&quot;
        ///    ],
        ///    &quot;materialName&quot;: &quot;bat&quot;,
        ///    &quot;parts&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;head&quot;,
        ///        &quot;children&quot;: [
        ///          { &quot;name&quot;: &quot;rightEar&quot; },
        ///          { &quot;name&quot;: &quot;leftEar&quot; }
        ///        ]
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;body&quot;,
        ///        &quot;children&quot;: [
        ///          {
        ///            &quot;name&quot;: &quot;rightWing&quot;,
        ///            &quot;children&quot;: [
        ///              { &quot;name&quot;: &quot;rightWingTip&quot; }
        ///            ]
        ///          },
        ///          {
        ///            &quot;name&quot;: &quot;leftWing&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modelMetaData {
            get {
                return ResourceManager.GetString("modelMetaData", resourceCulture);
            }
        }
    }
}
